name: Build Orbit

on: [push, pull_request]

jobs:
  build:
    name: Build on JDK ${{ matrix.jdk }} ${{ matrix.os }}
    if: always()
    strategy:
      matrix:
        jdk: [ '8', '11' ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Sync Repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Build with Gradle
        run: ./gradlew build

